# Default values for api-service.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: simple-api-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: NodePort
  port: 5000

livenessProbe:
  httpGet:
    path: /data
    port: 5000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /data
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
